/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TesourariaRouteImport } from './routes/tesouraria'
import { Route as SugestoesRouteImport } from './routes/sugestoes'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MensagemDoDiaRouteImport } from './routes/mensagem-do-dia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosPlanteASementeRouteImport } from './routes/jogos/plante-a-semente'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TesourariaRoute = TesourariaRouteImport.update({
  id: '/tesouraria',
  path: '/tesouraria',
  getParentRoute: () => rootRouteImport,
} as any)
const SugestoesRoute = SugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagemDoDiaRoute = MensagemDoDiaRouteImport.update({
  id: '/mensagem-do-dia',
  path: '/mensagem-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosPlanteASementeRoute = JogosPlanteASementeRouteImport.update({
  id: '/jogos/plante-a-semente',
  path: '/jogos/plante-a-semente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/mensagem-do-dia': typeof MensagemDoDiaRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/radio': typeof RadioRoute
  '/sugestoes': typeof SugestoesRoute
  '/tesouraria': typeof TesourariaRoute
  '/transparencia': typeof TransparenciaRoute
  '/jogos/plante-a-semente': typeof JogosPlanteASementeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/mensagem-do-dia': typeof MensagemDoDiaRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/radio': typeof RadioRoute
  '/sugestoes': typeof SugestoesRoute
  '/tesouraria': typeof TesourariaRoute
  '/transparencia': typeof TransparenciaRoute
  '/jogos/plante-a-semente': typeof JogosPlanteASementeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/mensagem-do-dia': typeof MensagemDoDiaRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/radio': typeof RadioRoute
  '/sugestoes': typeof SugestoesRoute
  '/tesouraria': typeof TesourariaRoute
  '/transparencia': typeof TransparenciaRoute
  '/jogos/plante-a-semente': typeof JogosPlanteASementeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completar-perfil'
    | '/inicio'
    | '/login'
    | '/mensagem-do-dia'
    | '/painel'
    | '/perfil'
    | '/radio'
    | '/sugestoes'
    | '/tesouraria'
    | '/transparencia'
    | '/jogos/plante-a-semente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completar-perfil'
    | '/inicio'
    | '/login'
    | '/mensagem-do-dia'
    | '/painel'
    | '/perfil'
    | '/radio'
    | '/sugestoes'
    | '/tesouraria'
    | '/transparencia'
    | '/jogos/plante-a-semente'
  id:
    | '__root__'
    | '/'
    | '/completar-perfil'
    | '/inicio'
    | '/login'
    | '/mensagem-do-dia'
    | '/painel'
    | '/perfil'
    | '/radio'
    | '/sugestoes'
    | '/tesouraria'
    | '/transparencia'
    | '/jogos/plante-a-semente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  MensagemDoDiaRoute: typeof MensagemDoDiaRoute
  PainelRoute: typeof PainelRoute
  PerfilRoute: typeof PerfilRoute
  RadioRoute: typeof RadioRoute
  SugestoesRoute: typeof SugestoesRoute
  TesourariaRoute: typeof TesourariaRoute
  TransparenciaRoute: typeof TransparenciaRoute
  JogosPlanteASementeRoute: typeof JogosPlanteASementeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesouraria': {
      id: '/tesouraria'
      path: '/tesouraria'
      fullPath: '/tesouraria'
      preLoaderRoute: typeof TesourariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sugestoes': {
      id: '/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof SugestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagem-do-dia': {
      id: '/mensagem-do-dia'
      path: '/mensagem-do-dia'
      fullPath: '/mensagem-do-dia'
      preLoaderRoute: typeof MensagemDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/plante-a-semente': {
      id: '/jogos/plante-a-semente'
      path: '/jogos/plante-a-semente'
      fullPath: '/jogos/plante-a-semente'
      preLoaderRoute: typeof JogosPlanteASementeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  MensagemDoDiaRoute: MensagemDoDiaRoute,
  PainelRoute: PainelRoute,
  PerfilRoute: PerfilRoute,
  RadioRoute: RadioRoute,
  SugestoesRoute: SugestoesRoute,
  TesourariaRoute: TesourariaRoute,
  TransparenciaRoute: TransparenciaRoute,
  JogosPlanteASementeRoute: JogosPlanteASementeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
