/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TesourariaRouteImport } from './routes/tesouraria'
import { Route as SugestoesRouteImport } from './routes/sugestoes'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MensagemDoDiaRouteImport } from './routes/mensagem-do-dia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as FebRouteImport } from './routes/feb'
import { Route as EvangelizacaoRouteImport } from './routes/evangelizacao'
import { Route as ConfigurarMemoriaRouteImport } from './routes/configurar-memoria'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosIndexRouteImport } from './routes/jogos/index'
import { Route as JogosSemeadorMensagensRouteImport } from './routes/jogos/semeador-mensagens'
import { Route as JogosQuizEspiritaRouteImport } from './routes/jogos/quiz-espirita'
import { Route as JogosPlanteASementeRouteImport } from './routes/jogos/plante-a-semente'
import { Route as JogosMemoriaEvangelizacaoRouteImport } from './routes/jogos/memoria-evangelizacao'
import { Route as JogosCaminhoDaLuzRouteImport } from './routes/jogos/caminho-da-luz'
import { Route as JogosCacaPalavrasRouteImport } from './routes/jogos/caca-palavras'
import { Route as CasaSiglaRouteImport } from './routes/casa/$sigla'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TesourariaRoute = TesourariaRouteImport.update({
  id: '/tesouraria',
  path: '/tesouraria',
  getParentRoute: () => rootRouteImport,
} as any)
const SugestoesRoute = SugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagemDoDiaRoute = MensagemDoDiaRouteImport.update({
  id: '/mensagem-do-dia',
  path: '/mensagem-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const FebRoute = FebRouteImport.update({
  id: '/feb',
  path: '/feb',
  getParentRoute: () => rootRouteImport,
} as any)
const EvangelizacaoRoute = EvangelizacaoRouteImport.update({
  id: '/evangelizacao',
  path: '/evangelizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarMemoriaRoute = ConfigurarMemoriaRouteImport.update({
  id: '/configurar-memoria',
  path: '/configurar-memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIndexRoute = JogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosSemeadorMensagensRoute = JogosSemeadorMensagensRouteImport.update({
  id: '/jogos/semeador-mensagens',
  path: '/jogos/semeador-mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosQuizEspiritaRoute = JogosQuizEspiritaRouteImport.update({
  id: '/jogos/quiz-espirita',
  path: '/jogos/quiz-espirita',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosPlanteASementeRoute = JogosPlanteASementeRouteImport.update({
  id: '/jogos/plante-a-semente',
  path: '/jogos/plante-a-semente',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosMemoriaEvangelizacaoRoute =
  JogosMemoriaEvangelizacaoRouteImport.update({
    id: '/jogos/memoria-evangelizacao',
    path: '/jogos/memoria-evangelizacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const JogosCaminhoDaLuzRoute = JogosCaminhoDaLuzRouteImport.update({
  id: '/jogos/caminho-da-luz',
  path: '/jogos/caminho-da-luz',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosCacaPalavrasRoute = JogosCacaPalavrasRouteImport.update({
  id: '/jogos/caca-palavras',
  path: '/jogos/caca-palavras',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaSiglaRoute = CasaSiglaRouteImport.update({
  id: '/casa/$sigla',
  path: '/casa/$sigla',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/ajuda': typeof AjudaRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/configurar-memoria': typeof ConfigurarMemoriaRoute
  '/evangelizacao': typeof EvangelizacaoRoute
  '/feb': typeof FebRoute
  '/inicio': typeof InicioRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/mensagem-do-dia': typeof MensagemDoDiaRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/permissoes': typeof PermissoesRoute
  '/radio': typeof RadioRoute
  '/sugestoes': typeof SugestoesRoute
  '/tesouraria': typeof TesourariaRoute
  '/transparencia': typeof TransparenciaRoute
  '/casa/$sigla': typeof CasaSiglaRoute
  '/jogos/caca-palavras': typeof JogosCacaPalavrasRoute
  '/jogos/caminho-da-luz': typeof JogosCaminhoDaLuzRoute
  '/jogos/memoria-evangelizacao': typeof JogosMemoriaEvangelizacaoRoute
  '/jogos/plante-a-semente': typeof JogosPlanteASementeRoute
  '/jogos/quiz-espirita': typeof JogosQuizEspiritaRoute
  '/jogos/semeador-mensagens': typeof JogosSemeadorMensagensRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/ajuda': typeof AjudaRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/configurar-memoria': typeof ConfigurarMemoriaRoute
  '/evangelizacao': typeof EvangelizacaoRoute
  '/feb': typeof FebRoute
  '/inicio': typeof InicioRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/mensagem-do-dia': typeof MensagemDoDiaRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/permissoes': typeof PermissoesRoute
  '/radio': typeof RadioRoute
  '/sugestoes': typeof SugestoesRoute
  '/tesouraria': typeof TesourariaRoute
  '/transparencia': typeof TransparenciaRoute
  '/casa/$sigla': typeof CasaSiglaRoute
  '/jogos/caca-palavras': typeof JogosCacaPalavrasRoute
  '/jogos/caminho-da-luz': typeof JogosCaminhoDaLuzRoute
  '/jogos/memoria-evangelizacao': typeof JogosMemoriaEvangelizacaoRoute
  '/jogos/plante-a-semente': typeof JogosPlanteASementeRoute
  '/jogos/quiz-espirita': typeof JogosQuizEspiritaRoute
  '/jogos/semeador-mensagens': typeof JogosSemeadorMensagensRoute
  '/jogos': typeof JogosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/ajuda': typeof AjudaRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/configurar-memoria': typeof ConfigurarMemoriaRoute
  '/evangelizacao': typeof EvangelizacaoRoute
  '/feb': typeof FebRoute
  '/inicio': typeof InicioRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/mensagem-do-dia': typeof MensagemDoDiaRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/permissoes': typeof PermissoesRoute
  '/radio': typeof RadioRoute
  '/sugestoes': typeof SugestoesRoute
  '/tesouraria': typeof TesourariaRoute
  '/transparencia': typeof TransparenciaRoute
  '/casa/$sigla': typeof CasaSiglaRoute
  '/jogos/caca-palavras': typeof JogosCacaPalavrasRoute
  '/jogos/caminho-da-luz': typeof JogosCaminhoDaLuzRoute
  '/jogos/memoria-evangelizacao': typeof JogosMemoriaEvangelizacaoRoute
  '/jogos/plante-a-semente': typeof JogosPlanteASementeRoute
  '/jogos/quiz-espirita': typeof JogosQuizEspiritaRoute
  '/jogos/semeador-mensagens': typeof JogosSemeadorMensagensRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/ajuda'
    | '/completar-perfil'
    | '/configurar-memoria'
    | '/evangelizacao'
    | '/feb'
    | '/inicio'
    | '/kanban'
    | '/login'
    | '/mensagem-do-dia'
    | '/painel'
    | '/perfil'
    | '/permissoes'
    | '/radio'
    | '/sugestoes'
    | '/tesouraria'
    | '/transparencia'
    | '/casa/$sigla'
    | '/jogos/caca-palavras'
    | '/jogos/caminho-da-luz'
    | '/jogos/memoria-evangelizacao'
    | '/jogos/plante-a-semente'
    | '/jogos/quiz-espirita'
    | '/jogos/semeador-mensagens'
    | '/jogos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/ajuda'
    | '/completar-perfil'
    | '/configurar-memoria'
    | '/evangelizacao'
    | '/feb'
    | '/inicio'
    | '/kanban'
    | '/login'
    | '/mensagem-do-dia'
    | '/painel'
    | '/perfil'
    | '/permissoes'
    | '/radio'
    | '/sugestoes'
    | '/tesouraria'
    | '/transparencia'
    | '/casa/$sigla'
    | '/jogos/caca-palavras'
    | '/jogos/caminho-da-luz'
    | '/jogos/memoria-evangelizacao'
    | '/jogos/plante-a-semente'
    | '/jogos/quiz-espirita'
    | '/jogos/semeador-mensagens'
    | '/jogos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/ajuda'
    | '/completar-perfil'
    | '/configurar-memoria'
    | '/evangelizacao'
    | '/feb'
    | '/inicio'
    | '/kanban'
    | '/login'
    | '/mensagem-do-dia'
    | '/painel'
    | '/perfil'
    | '/permissoes'
    | '/radio'
    | '/sugestoes'
    | '/tesouraria'
    | '/transparencia'
    | '/casa/$sigla'
    | '/jogos/caca-palavras'
    | '/jogos/caminho-da-luz'
    | '/jogos/memoria-evangelizacao'
    | '/jogos/plante-a-semente'
    | '/jogos/quiz-espirita'
    | '/jogos/semeador-mensagens'
    | '/jogos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AjudaRoute: typeof AjudaRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  ConfigurarMemoriaRoute: typeof ConfigurarMemoriaRoute
  EvangelizacaoRoute: typeof EvangelizacaoRoute
  FebRoute: typeof FebRoute
  InicioRoute: typeof InicioRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  MensagemDoDiaRoute: typeof MensagemDoDiaRoute
  PainelRoute: typeof PainelRoute
  PerfilRoute: typeof PerfilRoute
  PermissoesRoute: typeof PermissoesRoute
  RadioRoute: typeof RadioRoute
  SugestoesRoute: typeof SugestoesRoute
  TesourariaRoute: typeof TesourariaRoute
  TransparenciaRoute: typeof TransparenciaRoute
  CasaSiglaRoute: typeof CasaSiglaRoute
  JogosCacaPalavrasRoute: typeof JogosCacaPalavrasRoute
  JogosCaminhoDaLuzRoute: typeof JogosCaminhoDaLuzRoute
  JogosMemoriaEvangelizacaoRoute: typeof JogosMemoriaEvangelizacaoRoute
  JogosPlanteASementeRoute: typeof JogosPlanteASementeRoute
  JogosQuizEspiritaRoute: typeof JogosQuizEspiritaRoute
  JogosSemeadorMensagensRoute: typeof JogosSemeadorMensagensRoute
  JogosIndexRoute: typeof JogosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesouraria': {
      id: '/tesouraria'
      path: '/tesouraria'
      fullPath: '/tesouraria'
      preLoaderRoute: typeof TesourariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sugestoes': {
      id: '/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof SugestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagem-do-dia': {
      id: '/mensagem-do-dia'
      path: '/mensagem-do-dia'
      fullPath: '/mensagem-do-dia'
      preLoaderRoute: typeof MensagemDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feb': {
      id: '/feb'
      path: '/feb'
      fullPath: '/feb'
      preLoaderRoute: typeof FebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evangelizacao': {
      id: '/evangelizacao'
      path: '/evangelizacao'
      fullPath: '/evangelizacao'
      preLoaderRoute: typeof EvangelizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar-memoria': {
      id: '/configurar-memoria'
      path: '/configurar-memoria'
      fullPath: '/configurar-memoria'
      preLoaderRoute: typeof ConfigurarMemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/': {
      id: '/jogos/'
      path: '/jogos'
      fullPath: '/jogos/'
      preLoaderRoute: typeof JogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/semeador-mensagens': {
      id: '/jogos/semeador-mensagens'
      path: '/jogos/semeador-mensagens'
      fullPath: '/jogos/semeador-mensagens'
      preLoaderRoute: typeof JogosSemeadorMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/quiz-espirita': {
      id: '/jogos/quiz-espirita'
      path: '/jogos/quiz-espirita'
      fullPath: '/jogos/quiz-espirita'
      preLoaderRoute: typeof JogosQuizEspiritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/plante-a-semente': {
      id: '/jogos/plante-a-semente'
      path: '/jogos/plante-a-semente'
      fullPath: '/jogos/plante-a-semente'
      preLoaderRoute: typeof JogosPlanteASementeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/memoria-evangelizacao': {
      id: '/jogos/memoria-evangelizacao'
      path: '/jogos/memoria-evangelizacao'
      fullPath: '/jogos/memoria-evangelizacao'
      preLoaderRoute: typeof JogosMemoriaEvangelizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/caminho-da-luz': {
      id: '/jogos/caminho-da-luz'
      path: '/jogos/caminho-da-luz'
      fullPath: '/jogos/caminho-da-luz'
      preLoaderRoute: typeof JogosCaminhoDaLuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/caca-palavras': {
      id: '/jogos/caca-palavras'
      path: '/jogos/caca-palavras'
      fullPath: '/jogos/caca-palavras'
      preLoaderRoute: typeof JogosCacaPalavrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa/$sigla': {
      id: '/casa/$sigla'
      path: '/casa/$sigla'
      fullPath: '/casa/$sigla'
      preLoaderRoute: typeof CasaSiglaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AjudaRoute: AjudaRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  ConfigurarMemoriaRoute: ConfigurarMemoriaRoute,
  EvangelizacaoRoute: EvangelizacaoRoute,
  FebRoute: FebRoute,
  InicioRoute: InicioRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  MensagemDoDiaRoute: MensagemDoDiaRoute,
  PainelRoute: PainelRoute,
  PerfilRoute: PerfilRoute,
  PermissoesRoute: PermissoesRoute,
  RadioRoute: RadioRoute,
  SugestoesRoute: SugestoesRoute,
  TesourariaRoute: TesourariaRoute,
  TransparenciaRoute: TransparenciaRoute,
  CasaSiglaRoute: CasaSiglaRoute,
  JogosCacaPalavrasRoute: JogosCacaPalavrasRoute,
  JogosCaminhoDaLuzRoute: JogosCaminhoDaLuzRoute,
  JogosMemoriaEvangelizacaoRoute: JogosMemoriaEvangelizacaoRoute,
  JogosPlanteASementeRoute: JogosPlanteASementeRoute,
  JogosQuizEspiritaRoute: JogosQuizEspiritaRoute,
  JogosSemeadorMensagensRoute: JogosSemeadorMensagensRoute,
  JogosIndexRoute: JogosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
